print("Team 1:")
team1_name = input("Team Name:\n")
team1_score = input("Score:\n")
team1_overs = input("Overs played:\n")
print("Team 2:")
team2_name = input("Team Name:\n")
team2_score = input("Score:\n")
team2_overs = input("Overs played:\n")
print("\nMatch Details:")
print(f"Team 1:\nName: {team1_name}\nScore: {team1_score}\nOvers played: {team1_overs}")
print(f"Team 2:\nName: {team2_name}\nScore: {team2_score}\nOvers played: {team2_overs}")
